### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by grahamperrin** [willemliu/universal-comments-plugin#3]
Release notes are empty: 

https://addons.mozilla.org/en-GB/firefox/addon/universal-comments/versions/0.8/updateinfo/

https://addons.mozilla.org/en-GB/firefox/addon/universal-comments/versions/0.9/updateinfo/

https://addons.mozilla.org/en-GB/firefox/addon/universal-comments/versions/0.10/updateinfo/

https://addons.mozilla.org/en-GB/firefox/addon/universal-comments/versions/0.11/updateinfo/

https://addons.mozilla.org/en-GB/firefox/addon/universal-comments/versions/0.12/updateinfo/

For code audit and other purposes, please make it habit to publish notes. 

Thank you.

**Comment by willemliu** [comment]
I have added release notes for the plugin. But it seems that they are not always visible when at a different locale. See working links below:

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.8/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.9/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.10/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.11/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.12/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.13/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.14/updateinfo/

https://addons.mozilla.org/nl/firefox/addon/universal-comments/versions/0.15/updateinfo/

**Comment by grahamperrin** [comment]
Thank you. 

The locale issue is vaguely familiar. If I find a matching bug report I'll let you know.
