### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by grahamperrin** [willemliu/universal-comments-plugin#4]
https://raw.githubusercontent.com/willemliu/universal-comments/master/20200118privacy.txt

* should be linked from https://addons.mozilla.org/addon/universal-comments/
* should be available _prior_ to installation. 

(This might be an AMO policy issue.)

**Comment by willemliu** [comment]
I've added the privacy text so it's directly accessibly via: https://addons.mozilla.org/addon/universal-comments/
