### ISSUE TITLE
An unexpected error has occurred. – tracking protection

### ISSUE THREAD

**Issue by grahamperrin** [willemliu/universal-comments-plugin#5]
![image](https://user-images.githubusercontent.com/192271/72779925-4ce0c480-3c15-11ea-974e-caca5a107207.png)

https://github.com/willemliu/universal-comments-plugin/search?q=facebook&unscoped_q=facebook finds no mention of *facebook.net* in this repo. 

Is https://github.com/willemliu/universal-comments/commit/b56f1542b561531f57f60e601197f80ee17baa0e somehow related?

**Comment by grahamperrin** [comment]
To clarify: the issue (the unexpected errors) was **not** worked around by temporarily allowing all scripts for a page. 

---

Eventually I realised, version 0.12 of the extension is troublesome with tracking protection in Waterfox Classic (2019.12): 

![2020-01-21 07:28:31](https://user-images.githubusercontent.com/192271/72784486-d6e25a80-3c20-11ea-945b-6fa1590ea294.png)

![2020-01-21 07:29:12](https://user-images.githubusercontent.com/192271/72784495-db0e7800-3c20-11ea-86ec-94d95cf5dbe0.png)

about:preferences does not allow addition of exceptions, so to begin working around the issue it was necessary to: 

1. visit https://universal-comments.willemliu.now.sh/
2. disable tracking protection for the site …

![2020-01-21 07:31:20](https://user-images.githubusercontent.com/192271/72784633-29bc1200-3c21-11ea-9de7-ccf2ecdd1d36.png)

… however this one exception is not enough for the extension to work: 

![2020-01-21 07:34:01](https://user-images.githubusercontent.com/192271/72784647-2e80c600-3c21-11ea-8cb5-8dd1821a1069.png)

Please: 

* at which other sites must tracking be allowed?

**Comment by willemliu** [comment]
> ![image](https://user-images.githubusercontent.com/192271/72779925-4ce0c480-3c15-11ea-974e-caca5a107207.png)
> 
> https://github.com/willemliu/universal-comments-plugin/search?q=facebook&unscoped_q=facebook finds no mention of _facebook.net_ in this repo.
> 
> Is [willemliu/universal-comments@b56f154](https://github.com/willemliu/universal-comments/commit/b56f1542b561531f57f60e601197f80ee17baa0e) somehow related?

To answer your first question: `universal-comments` is related to `universal-comments-plugin`. The `universal-comments` repository holds the code for the backend (website) which powers the plugin.

**Comment by willemliu** [comment]
The plugin currently offers 2-ways of logging in:
1) Facebook account
2) Google account

It uses the Facebook SDK and Google SDK respectively and that's probably why it triggers your browsers' tracking protection.

**Comment by willemliu** [comment]
The following domains are necessary for the Facebook login:

www.facebook.com
staticxx.facebook.com

The latest version of the plugin (v0.15) can work even when the social media scripts are being blocked by your browser. However you will not be able to login using Facebook. You can still login using your Google account.

**Comment by willemliu** [comment]
Work-around for social media blockers implemented.

**Comment by grahamperrin** [comment]
If I disable tracking protection then I can sign in (with Google) and add a comment. One comment at <https://pastebin.com/h3Qsb7bT> as an example. 

With protection re-enabled and the page reloaded: I get a count (1) in the Universal Comments overlay but when the overlay is opened, 

> An unexpected error has occurred.

**Comment by willemliu** [comment]
> If I disable tracking protection then I can sign in (with Google) and add a comment. One comment at https://pastebin.com/h3Qsb7bT as an example.
> 
> With protection re-enabled and the page reloaded: I get a count (1) in the Universal Comments overlay but when the overlay is opened,
> 
> > An unexpected error has occurred.

I'll take another look at it.

**Comment by willemliu** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1226498

Apparently tracking protection is on by default. And specific domains have been blacklisted like for Facebook and Google SDK calls. I don't think I can fix this on my side unless I implement a completely different login solution.
For now I'll add the work-around to description until I have an alternative login solution.

**Comment by willemliu** [comment]
![image](https://user-images.githubusercontent.com/974906/72972614-0f726780-3dcc-11ea-955d-3a9b9863330e.png)
I've added a message when the Social Login API's can't be loaded to let the user know that the scripts have been blocked by the browser.

**Comment by willemliu** [comment]
@grahamperrin I've now implemented a new login provider (auth0). Maybe this will work better for you.
